type Post {
  id: ID!
  author: String!
  title: String
  subtitle: String
  image: String
  createdAt: String!
  updatedAt: String!
}

type Posts {
  cursor: ID!
  posts: [Post]
}

extend type Query {
  post(id: ID!): Post
  posts(cursor: ID): Posts
}
